# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-19 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crunchbase', '0002_auto_20160419_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbdegrees',
            name='object_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='crunchbase.CbObjects'),
        ),
        migrations.AlterField(
            model_name='cbrelationships',
            name='person_object_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employers', to='crunchbase.CbObjects'),
        ),
        migrations.AlterField(
            model_name='cbrelationships',
            name='relationship_object_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='crunchbase.CbObjects'),
        ),
    ]
